I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 234, in script
    main_ch "Fourteen talented students. But no clues on their talents here."
TypeError: 'str' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 234, in script
    main_ch "Fourteen talented students. But no clues on their talents here."
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\character.py", line 1352, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\character.py", line 1003, in do_display
    display_say(who,
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\character.py", line 693, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\display\core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\display\core.py", line 4543, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\display\layout.py", line 1179, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\display\layout.py", line 1179, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\display\layout.py", line 1179, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\display\behavior.py", line 528, in event
    rv = run(action)
  File "D:\PROGRAMS\renpy-8.0.3-sdk\renpy\display\behavior.py", line 379, in run
    return action(*args, **kwargs)
TypeError: 'str' object is not callable

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
a_day_for_the_dead 1.0
Wed May 21 00:21:49 2025
